spring:
  datasource:
    url: jdbc:mysql://localhost:3306/department_db
    username: root
    password: ROOT1234
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
server:
  port: 8888
eureka:
  instance:
    client:
      serverUrl:
        defaultZone: http://localhost:8761/eureka

